export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

export const USER_REG = "USER_REG";
export const USER_REG_SUCCESS = "USER_REG_SUCCESS";
export const USER_REG_FAILED = "USER_REG_FAILED";

export const USER_UPDATE = "USER_UPDATE";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAILED = "USER_UPDATE_FAILED";

export const NOTES_LIST_REQ = "NOTES_LIST_REQ";
export const NOTES_LIST_REQ_SUCCESS = "NOTES_LIST_REQ_SUCCESS";
export const NOTES_LIST_REQ_FAILED = "NOTES_LIST_REQ_FAILED";

export const NOTES_CREATE_REQ = "NOTES_CREATE_REQ";
export const NOTES_CREATE_REQ_SUCCESS = "NOTES_CREATE_REQ_SUCCESS";
export const NOTES_CREATE_REQ_FAILED = "NOTES_CREATE_REQ_FAILED";

export const NOTES_UPDATE_REQ = "NOTES_UPDATE_REQ";
export const NOTES_UPDATE_REQ_SUCCESS = "NOTES_UPDATE_REQ_SUCCESS";
export const NOTES_UPDATE_REQ_FAILED = "NOTES_UPDATE_REQ_FAILED";
export const NOTES_UPDATE_SET_NOTE = "NOTES_UPDATE_SET_NOTE";

export const NOTES_DELETE_REQ = "NOTES_DELETE_REQ";
export const NOTES_DELETE_REQ_SUCCESS = "NOTES_DELETE_REQ_SUCCESS";
export const NOTES_DELETE_REQ_FAILED = "NOTES_DELETE_REQ_FAILED";
